linters:
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - gocritic
    - gocyclo
    - misspell
    - noctx
    - nolintlint
    - perfsprint
    - revive
    - tagliatelle
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - wastedassign

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/pkg/errors
            desc: "use errors.New() instead"
          - pkg: github.com/sirupsen/logrus
            desc: "use log/slog instead"
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - noctx
        - perfsprint
    - path: third_party$
      text: ".*"
    - path: builtin$
      text: ".*"
    - path: examples$
      text: ".*"