pipeline:
  name: go-kit
  steps:
    - setup
    - build
    - test
  coverage: 30
  skip_push: false
  only_build: false
  only_test: false
  verbose: false
  go_version: "1.25.1"

service:
  name: "test-service"
  version: "1.0.0"
  environment: "dev"

registry:
  base_url: "test-registry"
  user: "test-user"
  pass: "test-pass"
  image: "test-image"
  tag: "test-tag"

git:
  repo: "test-repo"
  ref: "main"
  protocol: "https"
  user_email: "test@example.com"
  user_name: "test-user"
  ssh_key: ""

security:
  enable_vuln_check: true
  enable_linting: true
  lint_timeout: "1m"
  exclude_patterns: []

logging:
  level: "info"
  format: "json"
  sampling_enable: false
  sampling_rate: 1.0
  sampling_interval: "1s"

release:
  enabled: false
  use_goreleaser: false
  build_targets: []
  archive_formats: []
  checksum: false
  sign: false

dagger:
  log_output: false
  timeout: "1m"